# Mock Kubernetes nodes that correlate with EC2 instances in LocalStack.
# These nodes have providerIDs that Lumina uses to correlate with EC2 data.
# The instance IDs (i-xxxxxxxxxxxxxxxxx) will be created by LocalStack's seed script.
#
# NOTE: LocalStack generates predictable instance IDs, so these should match.
# If they don't match, Lumina will still expose metrics but won't correlate with nodes.
#
# For Veneer development, the important thing is that Lumina exposes metrics
# for the instance types (m5.xlarge, c5.large, r5.large) that we can use to
# test NodeOverlay decision logic.

apiVersion: v1
kind: Node
metadata:
  name: veneer-dev-node-1
  labels:
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    node.kubernetes.io/instance-type: m5.xlarge
    topology.kubernetes.io/zone: us-west-2a
    topology.kubernetes.io/region: us-west-2
spec:
  # ProviderID format: aws:///ZONE/INSTANCE_ID
  # LocalStack generates sequential instance IDs starting from i-00000000000000001
  providerID: aws:///us-west-2a/i-00000000000000001
status:
  capacity:
    cpu: "4"
    memory: 16Gi
    pods: "110"
  allocatable:
    cpu: "3920m"
    memory: 15Gi
    pods: "110"
  conditions:
    - type: Ready
      status: "True"
      reason: KubeletReady
      message: kubelet is posting ready status
---
apiVersion: v1
kind: Node
metadata:
  name: veneer-dev-node-2
  labels:
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    node.kubernetes.io/instance-type: m5.xlarge
    topology.kubernetes.io/zone: us-west-2a
    topology.kubernetes.io/region: us-west-2
spec:
  providerID: aws:///us-west-2a/i-00000000000000002
status:
  capacity:
    cpu: "4"
    memory: 16Gi
    pods: "110"
  allocatable:
    cpu: "3920m"
    memory: 15Gi
    pods: "110"
  conditions:
    - type: Ready
      status: "True"
      reason: KubeletReady
      message: kubelet is posting ready status
---
apiVersion: v1
kind: Node
metadata:
  name: veneer-dev-node-3
  labels:
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    node.kubernetes.io/instance-type: m5.xlarge
    topology.kubernetes.io/zone: us-west-2a
    topology.kubernetes.io/region: us-west-2
spec:
  providerID: aws:///us-west-2a/i-00000000000000003
status:
  capacity:
    cpu: "4"
    memory: 16Gi
    pods: "110"
  allocatable:
    cpu: "3920m"
    memory: 15Gi
    pods: "110"
  conditions:
    - type: Ready
      status: "True"
      reason: KubeletReady
      message: kubelet is posting ready status
---
apiVersion: v1
kind: Node
metadata:
  name: veneer-dev-node-4
  labels:
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    node.kubernetes.io/instance-type: c5.large
    topology.kubernetes.io/zone: us-west-2a
    topology.kubernetes.io/region: us-west-2
spec:
  providerID: aws:///us-west-2a/i-00000000000000004
status:
  capacity:
    cpu: "2"
    memory: 4Gi
    pods: "110"
  allocatable:
    cpu: "1920m"
    memory: 3Gi
    pods: "110"
  conditions:
    - type: Ready
      status: "True"
      reason: KubeletReady
      message: kubelet is posting ready status
---
apiVersion: v1
kind: Node
metadata:
  name: veneer-dev-node-5
  labels:
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    node.kubernetes.io/instance-type: c5.large
    topology.kubernetes.io/zone: us-west-2a
    topology.kubernetes.io/region: us-west-2
spec:
  providerID: aws:///us-west-2a/i-00000000000000005
status:
  capacity:
    cpu: "2"
    memory: 4Gi
    pods: "110"
  allocatable:
    cpu: "1920m"
    memory: 3Gi
    pods: "110"
  conditions:
    - type: Ready
      status: "True"
      reason: KubeletReady
      message: kubelet is posting ready status
---
apiVersion: v1
kind: Node
metadata:
  name: veneer-dev-node-6
  labels:
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    node.kubernetes.io/instance-type: r5.large
    topology.kubernetes.io/zone: us-west-2a
    topology.kubernetes.io/region: us-west-2
spec:
  providerID: aws:///us-west-2a/i-00000000000000006
status:
  capacity:
    cpu: "2"
    memory: 16Gi
    pods: "110"
  allocatable:
    cpu: "1920m"
    memory: 15Gi
    pods: "110"
  conditions:
    - type: Ready
      status: "True"
      reason: KubeletReady
      message: kubelet is posting ready status
---
apiVersion: v1
kind: Node
metadata:
  name: veneer-dev-node-7
  labels:
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    node.kubernetes.io/instance-type: r5.large
    topology.kubernetes.io/zone: us-west-2a
    topology.kubernetes.io/region: us-west-2
spec:
  providerID: aws:///us-west-2a/i-00000000000000007
status:
  capacity:
    cpu: "2"
    memory: 16Gi
    pods: "110"
  allocatable:
    cpu: "1920m"
    memory: 15Gi
    pods: "110"
  conditions:
    - type: Ready
      status: "True"
      reason: KubeletReady
      message: kubelet is posting ready status
---
# Spot instance node
apiVersion: v1
kind: Node
metadata:
  name: veneer-dev-node-spot-1
  labels:
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    node.kubernetes.io/instance-type: m5.large
    topology.kubernetes.io/zone: us-west-2a
    topology.kubernetes.io/region: us-west-2
    # Karpenter uses this label for spot instances
    karpenter.sh/capacity-type: spot
spec:
  providerID: aws:///us-west-2a/i-00000000000000008
status:
  capacity:
    cpu: "2"
    memory: 8Gi
    pods: "110"
  allocatable:
    cpu: "1920m"
    memory: 7Gi
    pods: "110"
  conditions:
    - type: Ready
      status: "True"
      reason: KubeletReady
      message: kubelet is posting ready status
