apiVersion: v1
kind: ServiceAccount
metadata:
  name: lumina-controller
  namespace: lumina-system
  labels:
    app.kubernetes.io/name: lumina
    app.kubernetes.io/part-of: veneer-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lumina-controller
  labels:
    app.kubernetes.io/name: lumina
    app.kubernetes.io/part-of: veneer-dev
rules:
  # Lumina needs to watch nodes to correlate with EC2 instances
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lumina-controller
  labels:
    app.kubernetes.io/name: lumina
    app.kubernetes.io/part-of: veneer-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lumina-controller
subjects:
  - kind: ServiceAccount
    name: lumina-controller
    namespace: lumina-system
